---
functional:
  - При нажатии на кнопку "Посмотреть программу" страница должна возвращаться в исходное положение
  - При вводе слова в поисковую строку должна появляться иконка крестика
  - При нажатии на иконку крестика в поисковой строке текст должен стираться
  - При нажатии на кнопки "Home", "Features", "Pricing", "FAQs", "About" страница должна возвращаться в исходное положение
non-functional:
  - Шапка сайта должна быть в одну строку
  - Шапка сайта должна быть цвета #212529
  - Шапка сайта должна быть в верхней части сайта 
  - Текст блока "Фронтенд-разработчик" имеет отступ 16рх
  - Размер элемента div c кнопкой "Начать учиться" должен быть 553.83х48
  - Размер заголовка "Учим необходимому" должен быть 1.75rem 
  - Список инструментов и навыков должен быть расположен в две колонки
implicit:
  - На сайте должныть быть кнпоки "Войти" и "Регистрация" 